name: Check Specs & Metadata
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [tlaplus-dispatch]

jobs:
  call-validation-workflow:
    strategy:
      matrix:
        include:
        - { os: windows-latest }
        - { os: ubuntu-latest }
       #- { os: macos-latest } https://github.com/tlaplus/Examples/issues/119
      fail-fast: false
    uses: tlaplus/examples/.github/workflows/validate.yml
    with:
      os: ${{ matrix.os }}

