name: Check Specs & Metadata
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [tlaplus-dispatch]

jobs:
  validate:
    name: Validate Manifest, Specs, & Models
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macOS not used; see https://github.com/tlaplus/Examples/issues/119
        os: [windows-latest, ubuntu-latest]
        unicode: [true, false]
      fail-fast: false
    env:
      SCRIPT_DIR: .github/scripts
      DEPS_DIR: deps
    defaults:
      run:
        shell: bash
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
      - name: Download TLA⁺ dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: $SCRIPT_DIR/windows-setup.sh $SCRIPT_DIR $DEPS_DIR false
      - name: Download TLA⁺ dependencies (Linux & macOS)
        if: matrix.os != 'windows-latest'
        run: $SCRIPT_DIR/linux-setup.sh $SCRIPT_DIR $DEPS_DIR false
      - name: Check manifest.json format
        run: |
          python $SCRIPT_DIR/check_manifest_schema.py \
            --manifest_path manifest.json             \
            --schema_path manifest-schema.json
      - name: Check manifest files
        run: |
          python $SCRIPT_DIR/check_manifest_files.py  \
            --manifest_path manifest.json             \
            --ci_ignore_path .ciignore
      - name: Check manifest feature flags
        run: |
          python $SCRIPT_DIR/check_manifest_features.py \
            --manifest_path manifest.json               \
            --ts_path $DEPS_DIR/tree-sitter-tlaplus
      - name: Check README spec table
        run: |
          python $SCRIPT_DIR/check_markdown_table.py  \
            --manifest_path manifest.json             \
            --readme_path README.md
      - name: Convert specs to unicode
        if: matrix.unicode
        run: |
          python "$SCRIPT_DIR/unicode_conversion.py"  \
            --tlauc_path "$DEPS_DIR/tlauc/tlauc"      \
            --manifest_path "$EXAMPLES_DIR/manifest.json"
      - name: Add unicode shims
        if: matrix.unicode
        run: |
          python "$SCRIPT_DIR/unicode_number_set_shim.py" \
            --ts_path "$DEPS_DIR/tree-sitter-tlaplus"     \
            --manifest_path "$EXAMPLES_DIR/manifest.json"
      - name: Parse all modules
        run: |
          # Need to have a nonempty list to pass as a skip parameter
          SKIP=("does/not/exist")
          if [ ${{ matrix.unicode }} ]; then
            # These redefine Nat, Int, or Real so cannot be shimmed
            SKIP+=(
              "specifications/SpecifyingSystems/Standard/Naturals.tla"
              "specifications/SpecifyingSystems/Standard/Peano.tla"
              "specifications/SpecifyingSystems/Standard/Integers.tla"
              "specifications/SpecifyingSystems/Standard/Reals.tla"
              "specifications/SpecifyingSystems/Standard/ProtoReals.tla"
              "specifications/SpecifyingSystems/RealTime/MCRealTime.tla"
              "specifications/SpecifyingSystems/RealTime/MCRealTimeHourClock.tla"
            )
          fi
          python $SCRIPT_DIR/parse_modules.py                            \
            --tools_jar_path $DEPS_DIR/tools/tla2tools.jar               \
            --tlapm_lib_path $DEPS_DIR/tlapm/library                     \
            --community_modules_jar_path $DEPS_DIR/community/modules.jar \
            --manifest_path manifest.json
      - name: Check small models
        run: |
          # Need to have a nonempty list to pass as a skip parameter
          SKIP=("does/not/exist")
          if [ ${{ matrix.unicode }} ]; then
            # This redefines Real so cannot be shimmed
            SKIP+=("specifications/SpecifyingSystems/RealTime/MCRealTimeHourClock.cfg")
          fi
          python $SCRIPT_DIR/check_small_models.py                       \
            --tools_jar_path $DEPS_DIR/tools/tla2tools.jar               \
            --tlapm_lib_path $DEPS_DIR/tlapm/library                     \
            --community_modules_jar_path $DEPS_DIR/community/modules.jar \
            --manifest_path manifest.json
      - name: Smoke-test large models
        run: |
          # SimKnuthYao requires certain number of states to have been generated
          # before termination or else it fails. This makes it not amenable to
          # smoke testing.
          SKIP=("specifications/KnuthYao/SimKnuthYao.cfg")
          # SimTokenRing does not work on Windows systems.
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            SKIP+=("specifications/ewd426/SimTokenRing.cfg")
          fi
          python $SCRIPT_DIR/smoke_test_large_models.py                  \
            --tools_jar_path $DEPS_DIR/tools/tla2tools.jar               \
            --tlapm_lib_path $DEPS_DIR/tlapm/library                     \
            --community_modules_jar_path $DEPS_DIR/community/modules.jar \
            --manifest_path manifest.json                                \
            --skip "${SKIP[@]}"
      - name: Check proofs
        if: matrix.os != 'windows-latest' && !matrix.unicode
        run: |
          SKIP=(
            # Failing; see https://github.com/tlaplus/Examples/issues/67
            specifications/Bakery-Boulangerie/Bakery.tla
            specifications/Bakery-Boulangerie/Boulanger.tla
            specifications/Paxos/Consensus.tla
            specifications/PaxosHowToWinATuringAward/Consensus.tla
            specifications/lamport_mutex/LamportMutex_proofs.tla
            specifications/ewd998/EWD998_proof.tla
            specifications/byzpaxos/VoteProof.tla
            # Long-running; see https://github.com/tlaplus/tlapm/issues/85
            specifications/LoopInvariance/Quicksort.tla
            specifications/LoopInvariance/SumSequence.tla
            specifications/bcastByz/bcastByz.tla
            specifications/MisraReachability/ReachabilityProofs.tla
            specifications/byzpaxos/BPConProof.tla # Takes about 30 minutes
          )
          python $SCRIPT_DIR/check_proofs.py       \
            --tlapm_path $DEPS_DIR/tlapm-install   \
            --manifest_path manifest.json          \
            --skip "${SKIP[@]}"
      - name: Smoke-test manifest generation script
        run: |
          rm -r $DEPS_DIR/tree-sitter-tlaplus/build
          python $SCRIPT_DIR/generate_manifest.py \
            --manifest_path manifest.json         \
            --ci_ignore_path .ciignore            \
            --ts_path $DEPS_DIR/tree-sitter-tlaplus
          git diff -a

